name: Deploy to Vercel

on:
  push:
    branches:
      - release/development 
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Remove local Vercel config
        run: rm -rf .vercel

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel environment
        run: vercel pull --yes --environment=production --scope=ieee-sl --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build project
        run: vercel build --prod --scope=ieee-sl --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy project
        run: vercel deploy --prebuilt --prod --scope=ieee-sl --token=${{ secrets.VERCEL_TOKEN }}
